apiVersion: v1
kind: Pod
metadata:
  name: pythonall30
  namespace: vault-devsecops
spec:
  serviceAccountName: myapp-sa
  containers:
  - name: app
    image: vijay3sc/all30
    ports:
    - containerPort: 8000